[tool.poetry]
name = "pca-analysis"
version = "0.1.0"
description = ""
authors = ["OctaneOolong <62565951+OctaneOolong@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.1"
polars = "^1.4.1"
pandas = "^2.2.2"
duckdb = "^1.0.0"
matplotlib = "^3.9.2"
jupyter = "^1.0.0"
scikit-learn = "^1.5.1"
pyarrow = "^17.0.0"
seaborn = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
