[tool.poetry]
name = "pca_analysis"
version = "0.1.0"
description = ""
authors = ["OctaneOolong <62565951+OctaneOolong@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
black = "^24.8.0"
ipykernel = "^6.29.5"
jupyterlab-code-formatter = "^3.0.2"
jupyterlab-myst = "^2.4.2"
matplotlib = "^3.9.2"
polars = "^1.5.0"
pyarrow = "^17.0.0"
pyperclip = "^1.9.0"
python = "^3.12.2"
python-lsp-server = {extras = ["all"], version = "^1.12.0"}
scipy = "^1.14.1"
tensorly = "^0.8.1"
tensorly-viz = "^0.1.7"
pymatreader = "^1.0.0"
corcondia = "^0.1.1"
great-tables = "^0.11.0"
pytest = "^8.3.3"
project-toc = {git = "https://github.com/jonathanstathakis/project-toc.git"}
database-etl = {git = "https://github.com/jonathanstathakis/database_etl.git"}
xarray = "^2024.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
