[tool.poetry]
name = "pca-analysis"
version = "0.1.0"
description = ""
authors = ["OctaneOolong <62565951+OctaneOolong@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tf-nightly = "^2.17.0"
tensorly = "^0.8.1"
plotly = "^5.23.0"
tensorly-viz = "^0.1.7"
tabulate = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
