"""
Export the binary pump tables - solvent composition and timetable of a sample from its
.D dir. Options to access in runtime as pandas dataframes or export directly to database
under a 'bin_pump' schema.
"""

import duckdb as db

from .bin_pump_to_db_ import (
    get_bin_pump_tables as get_bin_pump_tables,
    sample_tables_to_db as sample_tables_to_db,
)


def bin_pump_to_db(
    dpath: str,
    con: db.DuckDBPyConnection,
) -> int:
    """
    Wrapper for `get_bin_pump_tables` and `sample_tables_to_db` returning the table number
    `tbl_num` generated by each extraction.
    """
    tables = get_bin_pump_tables(dpath)
    tbl_num = sample_tables_to_db(sample=tables, con=con)
    return tbl_num
